services:
  - type: web
    name: fintrackr
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python MyFin_NiceGUI_VF3_FINAL.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: STORAGE_SECRET
        sync: false
      - key: PORT
        value: 10000
